# Generated by Django 5.1.3 on 2025-01-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
