# Generated by Django 5.1.3 on 2025-01-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_data_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='company',
            new_name='profession',
        ),
    ]
