# Generated by Django 5.1.3 on 2025-01-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_company_data_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='data',
            name='profession',
        ),
        migrations.AddField(
            model_name='data',
            name='profession',
            field=models.ManyToManyField(blank=True, to='dashboard.profession'),
        ),
    ]
