# Generated by Django 5.1.3 on 2025-01-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_profession_remove_data_profession_data_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='profession',
        ),
        migrations.DeleteModel(
            name='Profession',
        ),
        migrations.AddField(
            model_name='data',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
